version: "3.9"

services:
  python-service:
    container_name: run-python-with-dependencies
    image: deliveryfee.azurecr.io/pythonapi:latest
    build: 
      context: ./app/
      dockerfile: Dockerfile  
    ports:
      - "5000:5000" 
